export const POSTS = [
  {
    _id: "1",
    text: "Pudding is the cutest boi in the world!!!",
    img: "/posts/post1.jpg",
    user: {
      username: "johndoe",
      profileImg: "/avatars/boy1.jpg",
      fullName: "John Doe",
    },
    comments: [
      {
        _id: "1",
        text: "So cute!",
        user: {
          username: "janedoe",
          profileImg: "/avatars/girl1.jpg",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "2",
    text: "Web dev is fun! 😊",
    user: {
      username: "johndoe",
      profileImg: "/avatars/boy2.jpg",
      fullName: "John Doe",
    },
    comments: [
      {
        _id: "1",
        text: "Yeaaah",
        user: {
          username: "janedoe",
          profileImg: "/avatars/girl2.jpg",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "3",
    text: "Some sushi on a wooden table, generated by Midjourney. 🚀",
    img: "/posts/post2.png",
    user: {
      username: "johndoe",
      profileImg: "/avatars/boy3.jpg",
      fullName: "John Doe",
    },
    comments: [],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
    ],
  },
  {
    _id: "4",
    text: "BIRFIA is the best game in the world!",
    img: "/posts/post3.png",
    user: {
      username: "johndoe",
      profileImg: "/avatars/boy3.jpg",
      fullName: "John Doe",
    },
    comments: [
      {
        _id: "1",
        text: "True",
        user: {
          username: "janedoe",
          profileImg: "/avatars/girl3.jpg",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
      "6658s897",
      "6658s898",
      "6658s899",
    ],
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    _id: "1",
    fullName: "John Doe",
    username: "johndoe",
    profileImg: "/avatars/boy2.jpg",
  },
  {
    _id: "2",
    fullName: "Jane Doe",
    username: "janedoe",
    profileImg: "/avatars/girl1.jpg",
  },
  {
    _id: "3",
    fullName: "Bob Doe",
    username: "bobdoe",
    profileImg: "/avatars/boy3.jpg",
  },
  {
    _id: "4",
    fullName: "Daisy Doe",
    username: "daisydoe",
    profileImg: "/avatars/girl2.jpg",
  },
];
